import { mkdir, existsSync } from "node:fs";
import { promisify } from "node:util";
import { join } from "node:path";
import chalk from "chalk";
import type { ScaffoldOptions } from "./types.ts";

const mkdirAsync = promisify(mkdir);

export async function scaffold(options: ScaffoldOptions) {
  const { projectName, targetDir, force } = options;

  if (existsSync(targetDir) && !force) {
    console.error(chalk.red(`Directory ${projectName} already exists. Use --force to overwrite.`));
    process.exit(1);
  }

  if (!existsSync(targetDir)) {
    await mkdirAsync(targetDir, { recursive: true });
  }

  console.log(chalk.green(`\nScaffolding project in ${targetDir}...`));

  // Placeholder for template copying logic
  await Bun.write(join(targetDir, "README.md"), `# ${projectName}\n\nGenerated by Ainab Stack CLI.`);
  
  console.log(chalk.blue(`\nDone! Now run:\n`));
  console.log(`  cd ${projectName}`);
  console.log(`  bun install`);
  console.log(`  bun dev\n`);
}
